Added utils dir to project
pietrik123/untitled-sdl-tank-game pull request #30
Opened 2019-02-03 08:46 UTC by dante7867

Some functions and structs added for another task just to fill the directory

2019-02-03 21:01 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
> +int distanceFromPointToLine(Line line, Point point)
please change calculation type to `float`

2019-02-03 21:02 UTC, pietrik123 requested changes
good work :) please change calculation type `int` -> `float` in all functions and structures

2019-02-05 19:48 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/figures.h
> +struct Round
please rename to `Circle`

2019-02-05 19:48 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
>  bool isRoundAndLineIntersecting(Line line, Round round)
please rename to `isCircleAndLineIntersecting`

2019-02-05 19:50 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
> +double coutDelta(double a, double b, double c)
please rename to `getDelta()`

2019-02-05 19:50 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
> +std::tuple<double, double> countSolutions(double a, double b, double c, double delta)
good idea :+1:

2019-02-05 19:51 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
> +		return std::make_tuple<double, double> ( (pow(b, 2) - sqrt(delta)) / (2 * a), ((pow(b, 2) + sqrt(delta)) / (2 * a)) );
what if `a == 0` ?

2019-02-05 19:56 UTC, pietrik123 requested changes
please check comments (renaming proposals mostly). Good job :+1:

2019-02-05 21:07 UTC, pietrik123 commented on untitled-sdl-tank-game/utils/utils.cpp
> +int distanceFromPointToLine(Line line, Point point)
Optionally (may be in different pull request) please add  some dummy unit tests by:
* adding dependent [project](https://github.com/pietrik123/untitled-sdl-tank-game/wiki/Add-a-project-to-a-Solution-in-MS-Visual) to repo (like [this)](https://github.com/pietrik123/untitled-sdl-tank-game/commit/9d5a40b80e7a3a4fc74982d723bea499bb6f6030#diff-900bcabb885a4243a6ce2c75b247bcec)
* adding *.cpp test file ([example](https://github.com/pietrik123/untitled-sdl-tank-game/blob/9d5a40b80e7a3a4fc74982d723bea499bb6f6030/test_dep_proj2/dummy_test.cpp))

2019-02-06 20:57 UTC, pietrik123 approved these changes
good job, please merge and close task :+1:

2019-02-07 22:10 UTC, dantefkr commented
can't create pull request:
### This branch has conflicts that must be resolved
Only those with [write access](https://help.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

2019-02-08 21:52 UTC, merged